FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
COPY MiniTwit.Tests/MiniTwit.Tests.csproj MiniTwit.Tests/
WORKDIR MiniTwit.Tests/
RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /app/wait_for_it.sh \
    && dotnet restore



